/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as OrganizationsSlugRouteImport } from './routes/organizations/$slug'
import { Route as OrganizationsSlugSettingsRouteImport } from './routes/organizations/$slug_.settings'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugRoute = OrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugSettingsRoute =
  OrganizationsSlugSettingsRouteImport.update({
    id: '/organizations/$slug_/settings',
    path: '/organizations/$slug/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/organizations/$slug/settings': typeof OrganizationsSlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/organizations/$slug/settings': typeof OrganizationsSlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/organizations/$slug_/settings': typeof OrganizationsSlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/organizations/$slug'
    | '/products/$slug'
    | '/organizations'
    | '/products'
    | '/organizations/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/organizations/$slug'
    | '/products/$slug'
    | '/organizations'
    | '/products'
    | '/organizations/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/organizations/$slug'
    | '/products/$slug'
    | '/organizations/'
    | '/products/'
    | '/organizations/$slug_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  OrganizationsSlugRoute: typeof OrganizationsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  OrganizationsSlugSettingsRoute: typeof OrganizationsSlugSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug_/settings': {
      id: '/organizations/$slug_/settings'
      path: '/organizations/$slug/settings'
      fullPath: '/organizations/$slug/settings'
      preLoaderRoute: typeof OrganizationsSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  OrganizationsSlugRoute: OrganizationsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  OrganizationsSlugSettingsRoute: OrganizationsSlugSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
