/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsProductsRouteImport } from './routes/settings/products'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsOrganizationsRouteImport } from './routes/settings/organizations'
import { Route as OauthSuccessRouteImport } from './routes/oauth/success'
import { Route as SettingsProductSlugRouteImport } from './routes/settings/product/$slug'
import { Route as SettingsOrgSlugRouteImport } from './routes/settings/org/$slug'
import { Route as AppOrgSlugProductSlugRouteImport } from './routes/app/$orgSlug/$productSlug'
import { Route as SettingsProductSlugIndexRouteImport } from './routes/settings/product/$slug/index'
import { Route as SettingsOrgSlugIndexRouteImport } from './routes/settings/org/$slug/index'
import { Route as AppOrgSlugProductSlugIndexRouteImport } from './routes/app/$orgSlug/$productSlug/index'
import { Route as SettingsProductSlugTeamRouteImport } from './routes/settings/product/$slug/team'
import { Route as SettingsProductSlugSourcesRouteImport } from './routes/settings/product/$slug/sources'
import { Route as SettingsProductSlugGeneralRouteImport } from './routes/settings/product/$slug/general'
import { Route as SettingsOrgSlugSeatsRouteImport } from './routes/settings/org/$slug/seats'
import { Route as SettingsOrgSlugProductsRouteImport } from './routes/settings/org/$slug/products'
import { Route as SettingsOrgSlugPlanRouteImport } from './routes/settings/org/$slug/plan'
import { Route as SettingsOrgSlugGeneralRouteImport } from './routes/settings/org/$slug/general'
import { Route as AppOrgSlugProductSlugTimelineRouteImport } from './routes/app/$orgSlug/$productSlug/timeline'
import { Route as AppOrgSlugProductSlugAiTestRouteImport } from './routes/app/$orgSlug/$productSlug/ai-test'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProductsRoute = SettingsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrganizationsRoute = SettingsOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SettingsRoute,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProductSlugRoute = SettingsProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrgSlugRoute = SettingsOrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => SettingsRoute,
} as any)
const AppOrgSlugProductSlugRoute = AppOrgSlugProductSlugRouteImport.update({
  id: '/app/$orgSlug/$productSlug',
  path: '/app/$orgSlug/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProductSlugIndexRoute =
  SettingsProductSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsProductSlugRoute,
  } as any)
const SettingsOrgSlugIndexRoute = SettingsOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsOrgSlugRoute,
} as any)
const AppOrgSlugProductSlugIndexRoute =
  AppOrgSlugProductSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrgSlugProductSlugRoute,
  } as any)
const SettingsProductSlugTeamRoute = SettingsProductSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsProductSlugRoute,
} as any)
const SettingsProductSlugSourcesRoute =
  SettingsProductSlugSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => SettingsProductSlugRoute,
  } as any)
const SettingsProductSlugGeneralRoute =
  SettingsProductSlugGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsProductSlugRoute,
  } as any)
const SettingsOrgSlugSeatsRoute = SettingsOrgSlugSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => SettingsOrgSlugRoute,
} as any)
const SettingsOrgSlugProductsRoute = SettingsOrgSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SettingsOrgSlugRoute,
} as any)
const SettingsOrgSlugPlanRoute = SettingsOrgSlugPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SettingsOrgSlugRoute,
} as any)
const SettingsOrgSlugGeneralRoute = SettingsOrgSlugGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsOrgSlugRoute,
} as any)
const AppOrgSlugProductSlugTimelineRoute =
  AppOrgSlugProductSlugTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppOrgSlugProductSlugRoute,
  } as any)
const AppOrgSlugProductSlugAiTestRoute =
  AppOrgSlugProductSlugAiTestRouteImport.update({
    id: '/ai-test',
    path: '/ai-test',
    getParentRoute: () => AppOrgSlugProductSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/oauth/success': typeof OauthSuccessRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/app/$orgSlug/$productSlug': typeof AppOrgSlugProductSlugRouteWithChildren
  '/settings/org/$slug': typeof SettingsOrgSlugRouteWithChildren
  '/settings/product/$slug': typeof SettingsProductSlugRouteWithChildren
  '/app/$orgSlug/$productSlug/ai-test': typeof AppOrgSlugProductSlugAiTestRoute
  '/app/$orgSlug/$productSlug/timeline': typeof AppOrgSlugProductSlugTimelineRoute
  '/settings/org/$slug/general': typeof SettingsOrgSlugGeneralRoute
  '/settings/org/$slug/plan': typeof SettingsOrgSlugPlanRoute
  '/settings/org/$slug/products': typeof SettingsOrgSlugProductsRoute
  '/settings/org/$slug/seats': typeof SettingsOrgSlugSeatsRoute
  '/settings/product/$slug/general': typeof SettingsProductSlugGeneralRoute
  '/settings/product/$slug/sources': typeof SettingsProductSlugSourcesRoute
  '/settings/product/$slug/team': typeof SettingsProductSlugTeamRoute
  '/app/$orgSlug/$productSlug/': typeof AppOrgSlugProductSlugIndexRoute
  '/settings/org/$slug/': typeof SettingsOrgSlugIndexRoute
  '/settings/product/$slug/': typeof SettingsProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/app/$orgSlug/$productSlug/ai-test': typeof AppOrgSlugProductSlugAiTestRoute
  '/app/$orgSlug/$productSlug/timeline': typeof AppOrgSlugProductSlugTimelineRoute
  '/settings/org/$slug/general': typeof SettingsOrgSlugGeneralRoute
  '/settings/org/$slug/plan': typeof SettingsOrgSlugPlanRoute
  '/settings/org/$slug/products': typeof SettingsOrgSlugProductsRoute
  '/settings/org/$slug/seats': typeof SettingsOrgSlugSeatsRoute
  '/settings/product/$slug/general': typeof SettingsProductSlugGeneralRoute
  '/settings/product/$slug/sources': typeof SettingsProductSlugSourcesRoute
  '/settings/product/$slug/team': typeof SettingsProductSlugTeamRoute
  '/app/$orgSlug/$productSlug': typeof AppOrgSlugProductSlugIndexRoute
  '/settings/org/$slug': typeof SettingsOrgSlugIndexRoute
  '/settings/product/$slug': typeof SettingsProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/oauth/success': typeof OauthSuccessRoute
  '/settings/organizations': typeof SettingsOrganizationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/products': typeof SettingsProductsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/app/$orgSlug/$productSlug': typeof AppOrgSlugProductSlugRouteWithChildren
  '/settings/org/$slug': typeof SettingsOrgSlugRouteWithChildren
  '/settings/product/$slug': typeof SettingsProductSlugRouteWithChildren
  '/app/$orgSlug/$productSlug/ai-test': typeof AppOrgSlugProductSlugAiTestRoute
  '/app/$orgSlug/$productSlug/timeline': typeof AppOrgSlugProductSlugTimelineRoute
  '/settings/org/$slug/general': typeof SettingsOrgSlugGeneralRoute
  '/settings/org/$slug/plan': typeof SettingsOrgSlugPlanRoute
  '/settings/org/$slug/products': typeof SettingsOrgSlugProductsRoute
  '/settings/org/$slug/seats': typeof SettingsOrgSlugSeatsRoute
  '/settings/product/$slug/general': typeof SettingsProductSlugGeneralRoute
  '/settings/product/$slug/sources': typeof SettingsProductSlugSourcesRoute
  '/settings/product/$slug/team': typeof SettingsProductSlugTeamRoute
  '/app/$orgSlug/$productSlug/': typeof AppOrgSlugProductSlugIndexRoute
  '/settings/org/$slug/': typeof SettingsOrgSlugIndexRoute
  '/settings/product/$slug/': typeof SettingsProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/oauth/success'
    | '/settings/organizations'
    | '/settings/preferences'
    | '/settings/products'
    | '/settings/profile'
    | '/organizations'
    | '/products'
    | '/settings/'
    | '/app/$orgSlug/$productSlug'
    | '/settings/org/$slug'
    | '/settings/product/$slug'
    | '/app/$orgSlug/$productSlug/ai-test'
    | '/app/$orgSlug/$productSlug/timeline'
    | '/settings/org/$slug/general'
    | '/settings/org/$slug/plan'
    | '/settings/org/$slug/products'
    | '/settings/org/$slug/seats'
    | '/settings/product/$slug/general'
    | '/settings/product/$slug/sources'
    | '/settings/product/$slug/team'
    | '/app/$orgSlug/$productSlug/'
    | '/settings/org/$slug/'
    | '/settings/product/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/oauth/success'
    | '/settings/organizations'
    | '/settings/preferences'
    | '/settings/products'
    | '/settings/profile'
    | '/organizations'
    | '/products'
    | '/settings'
    | '/app/$orgSlug/$productSlug/ai-test'
    | '/app/$orgSlug/$productSlug/timeline'
    | '/settings/org/$slug/general'
    | '/settings/org/$slug/plan'
    | '/settings/org/$slug/products'
    | '/settings/org/$slug/seats'
    | '/settings/product/$slug/general'
    | '/settings/product/$slug/sources'
    | '/settings/product/$slug/team'
    | '/app/$orgSlug/$productSlug'
    | '/settings/org/$slug'
    | '/settings/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/oauth/success'
    | '/settings/organizations'
    | '/settings/preferences'
    | '/settings/products'
    | '/settings/profile'
    | '/organizations/'
    | '/products/'
    | '/settings/'
    | '/app/$orgSlug/$productSlug'
    | '/settings/org/$slug'
    | '/settings/product/$slug'
    | '/app/$orgSlug/$productSlug/ai-test'
    | '/app/$orgSlug/$productSlug/timeline'
    | '/settings/org/$slug/general'
    | '/settings/org/$slug/plan'
    | '/settings/org/$slug/products'
    | '/settings/org/$slug/seats'
    | '/settings/product/$slug/general'
    | '/settings/product/$slug/sources'
    | '/settings/product/$slug/team'
    | '/app/$orgSlug/$productSlug/'
    | '/settings/org/$slug/'
    | '/settings/product/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  OauthSuccessRoute: typeof OauthSuccessRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AppOrgSlugProductSlugRoute: typeof AppOrgSlugProductSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/products': {
      id: '/settings/products'
      path: '/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof SettingsProductsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/organizations': {
      id: '/settings/organizations'
      path: '/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof SettingsOrganizationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/product/$slug': {
      id: '/settings/product/$slug'
      path: '/product/$slug'
      fullPath: '/settings/product/$slug'
      preLoaderRoute: typeof SettingsProductSlugRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/org/$slug': {
      id: '/settings/org/$slug'
      path: '/org/$slug'
      fullPath: '/settings/org/$slug'
      preLoaderRoute: typeof SettingsOrgSlugRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/$orgSlug/$productSlug': {
      id: '/app/$orgSlug/$productSlug'
      path: '/app/$orgSlug/$productSlug'
      fullPath: '/app/$orgSlug/$productSlug'
      preLoaderRoute: typeof AppOrgSlugProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/product/$slug/': {
      id: '/settings/product/$slug/'
      path: '/'
      fullPath: '/settings/product/$slug/'
      preLoaderRoute: typeof SettingsProductSlugIndexRouteImport
      parentRoute: typeof SettingsProductSlugRoute
    }
    '/settings/org/$slug/': {
      id: '/settings/org/$slug/'
      path: '/'
      fullPath: '/settings/org/$slug/'
      preLoaderRoute: typeof SettingsOrgSlugIndexRouteImport
      parentRoute: typeof SettingsOrgSlugRoute
    }
    '/app/$orgSlug/$productSlug/': {
      id: '/app/$orgSlug/$productSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/$productSlug/'
      preLoaderRoute: typeof AppOrgSlugProductSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugProductSlugRoute
    }
    '/settings/product/$slug/team': {
      id: '/settings/product/$slug/team'
      path: '/team'
      fullPath: '/settings/product/$slug/team'
      preLoaderRoute: typeof SettingsProductSlugTeamRouteImport
      parentRoute: typeof SettingsProductSlugRoute
    }
    '/settings/product/$slug/sources': {
      id: '/settings/product/$slug/sources'
      path: '/sources'
      fullPath: '/settings/product/$slug/sources'
      preLoaderRoute: typeof SettingsProductSlugSourcesRouteImport
      parentRoute: typeof SettingsProductSlugRoute
    }
    '/settings/product/$slug/general': {
      id: '/settings/product/$slug/general'
      path: '/general'
      fullPath: '/settings/product/$slug/general'
      preLoaderRoute: typeof SettingsProductSlugGeneralRouteImport
      parentRoute: typeof SettingsProductSlugRoute
    }
    '/settings/org/$slug/seats': {
      id: '/settings/org/$slug/seats'
      path: '/seats'
      fullPath: '/settings/org/$slug/seats'
      preLoaderRoute: typeof SettingsOrgSlugSeatsRouteImport
      parentRoute: typeof SettingsOrgSlugRoute
    }
    '/settings/org/$slug/products': {
      id: '/settings/org/$slug/products'
      path: '/products'
      fullPath: '/settings/org/$slug/products'
      preLoaderRoute: typeof SettingsOrgSlugProductsRouteImport
      parentRoute: typeof SettingsOrgSlugRoute
    }
    '/settings/org/$slug/plan': {
      id: '/settings/org/$slug/plan'
      path: '/plan'
      fullPath: '/settings/org/$slug/plan'
      preLoaderRoute: typeof SettingsOrgSlugPlanRouteImport
      parentRoute: typeof SettingsOrgSlugRoute
    }
    '/settings/org/$slug/general': {
      id: '/settings/org/$slug/general'
      path: '/general'
      fullPath: '/settings/org/$slug/general'
      preLoaderRoute: typeof SettingsOrgSlugGeneralRouteImport
      parentRoute: typeof SettingsOrgSlugRoute
    }
    '/app/$orgSlug/$productSlug/timeline': {
      id: '/app/$orgSlug/$productSlug/timeline'
      path: '/timeline'
      fullPath: '/app/$orgSlug/$productSlug/timeline'
      preLoaderRoute: typeof AppOrgSlugProductSlugTimelineRouteImport
      parentRoute: typeof AppOrgSlugProductSlugRoute
    }
    '/app/$orgSlug/$productSlug/ai-test': {
      id: '/app/$orgSlug/$productSlug/ai-test'
      path: '/ai-test'
      fullPath: '/app/$orgSlug/$productSlug/ai-test'
      preLoaderRoute: typeof AppOrgSlugProductSlugAiTestRouteImport
      parentRoute: typeof AppOrgSlugProductSlugRoute
    }
  }
}

interface SettingsOrgSlugRouteChildren {
  SettingsOrgSlugGeneralRoute: typeof SettingsOrgSlugGeneralRoute
  SettingsOrgSlugPlanRoute: typeof SettingsOrgSlugPlanRoute
  SettingsOrgSlugProductsRoute: typeof SettingsOrgSlugProductsRoute
  SettingsOrgSlugSeatsRoute: typeof SettingsOrgSlugSeatsRoute
  SettingsOrgSlugIndexRoute: typeof SettingsOrgSlugIndexRoute
}

const SettingsOrgSlugRouteChildren: SettingsOrgSlugRouteChildren = {
  SettingsOrgSlugGeneralRoute: SettingsOrgSlugGeneralRoute,
  SettingsOrgSlugPlanRoute: SettingsOrgSlugPlanRoute,
  SettingsOrgSlugProductsRoute: SettingsOrgSlugProductsRoute,
  SettingsOrgSlugSeatsRoute: SettingsOrgSlugSeatsRoute,
  SettingsOrgSlugIndexRoute: SettingsOrgSlugIndexRoute,
}

const SettingsOrgSlugRouteWithChildren = SettingsOrgSlugRoute._addFileChildren(
  SettingsOrgSlugRouteChildren,
)

interface SettingsProductSlugRouteChildren {
  SettingsProductSlugGeneralRoute: typeof SettingsProductSlugGeneralRoute
  SettingsProductSlugSourcesRoute: typeof SettingsProductSlugSourcesRoute
  SettingsProductSlugTeamRoute: typeof SettingsProductSlugTeamRoute
  SettingsProductSlugIndexRoute: typeof SettingsProductSlugIndexRoute
}

const SettingsProductSlugRouteChildren: SettingsProductSlugRouteChildren = {
  SettingsProductSlugGeneralRoute: SettingsProductSlugGeneralRoute,
  SettingsProductSlugSourcesRoute: SettingsProductSlugSourcesRoute,
  SettingsProductSlugTeamRoute: SettingsProductSlugTeamRoute,
  SettingsProductSlugIndexRoute: SettingsProductSlugIndexRoute,
}

const SettingsProductSlugRouteWithChildren =
  SettingsProductSlugRoute._addFileChildren(SettingsProductSlugRouteChildren)

interface SettingsRouteChildren {
  SettingsOrganizationsRoute: typeof SettingsOrganizationsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProductsRoute: typeof SettingsProductsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsOrgSlugRoute: typeof SettingsOrgSlugRouteWithChildren
  SettingsProductSlugRoute: typeof SettingsProductSlugRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsOrganizationsRoute: SettingsOrganizationsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProductsRoute: SettingsProductsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsOrgSlugRoute: SettingsOrgSlugRouteWithChildren,
  SettingsProductSlugRoute: SettingsProductSlugRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface AppOrgSlugProductSlugRouteChildren {
  AppOrgSlugProductSlugAiTestRoute: typeof AppOrgSlugProductSlugAiTestRoute
  AppOrgSlugProductSlugTimelineRoute: typeof AppOrgSlugProductSlugTimelineRoute
  AppOrgSlugProductSlugIndexRoute: typeof AppOrgSlugProductSlugIndexRoute
}

const AppOrgSlugProductSlugRouteChildren: AppOrgSlugProductSlugRouteChildren = {
  AppOrgSlugProductSlugAiTestRoute: AppOrgSlugProductSlugAiTestRoute,
  AppOrgSlugProductSlugTimelineRoute: AppOrgSlugProductSlugTimelineRoute,
  AppOrgSlugProductSlugIndexRoute: AppOrgSlugProductSlugIndexRoute,
}

const AppOrgSlugProductSlugRouteWithChildren =
  AppOrgSlugProductSlugRoute._addFileChildren(
    AppOrgSlugProductSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  OauthSuccessRoute: OauthSuccessRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AppOrgSlugProductSlugRoute: AppOrgSlugProductSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
